### ISSUE TITLE
trackers_uri is never assigned

### ISSUE THREAD

**Issue by CorralPeltzer** [sdmtr/electromagnet#1]
https://github.com/sdmtr/electromagnet/blob/cbb827c642a355b1b1f7eb51c3ca8ca6005349e9/src/inject.js#L15

`trackers` seems to be an Object, so `trackers.length` is `undefined` and `trackers_uri` never gets built.

**Comment by sdmtr** [comment]
Whoops, no idea how I managed to overlook that. I've fixed it in the next commit, cheers.
