### ISSUE TITLE
magnet is too long for Windows 10 to open

### ISSUE THREAD

**Issue by CorralPeltzer** [sdmtr/electromagnet#2]
In Windows 10, when the extension is enabled and the magnet link is modified, left click on the link doesn't open the application configured to handle `magnet:` links (my BitTorrent client). Instead, nothing happens.

This is due to the magnet link being too long (2934 characters right now with default trackers). Firefox opens this long link fine, but Chrome does not. Manually reducing the length, I have found the limit to be 2046 characters, also observed [here](https://superruub.wordpress.com/2013/05/30/mailto-protocol-character-limit/) and [here](https://stackoverflow.com/questions/13317429/mailto-max-length-of-each-internet-browsers).

I haven't tested this in other operating systems, but I'd recommend keeping the magnet shorter than 2000 characters to improve compatibility.

**Comment by sdmtr** [comment]
Thanks Corral, I hadn't tested this in Windows yet so I appreciate your feedback. I'll fix this in the next commit.
