### ISSUE TITLE
Firefox port?

### ISSUE THREAD

**Issue by AnimMouse** [sdmtr/electromagnet#3]
Can be this addon ported to Firefox?

**Comment by sdmtr** [comment]
I don't see why not, but I don't use Firefox and wouldn't know where to begin. I'll look into it though.

**Comment by AnimMouse** [comment]
Thanks! looking forward to the Firefox port.

**Comment by AnimMouse** [comment]
Well, according to Extension Compatibility Test for Firefox, there is a compatibility issue: 
extension.onMessage is not supported found in the following locations: inject.js:37
[report.json](https://github.com/sdmtr/electromagnet/files/4721417/report.txt)
Because of this, I can't automatically port this extension to Firefox.
